spring:
  application:
    name: whale-admin
  profiles:
    active: dev

# 端点指标监控 http://127.0.0.1:21002/actuator/health
management:
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        include: '*'
        # 在 include 的基础上，需要排除的端点。通过设置 * ，可以排除所有端点。
        exclude:

# swagger?http://127.0.0.1:21002/swagger-ui/index.html?
springfox:
  documentation:
    enabled: true
swagger:
  title: whale-admin
  description: whale-admin
  version: 1.4.0.RELEASE
  base-package: com.whale
  base-path: /**
  exclude-path: /error, /ops/**
  contact:
    email: xxx@xxx.com
    name: xxx
    url: xxx
  host: xxx
  license:
  licenseUrl:
  termsOfServiceUrl:
  globalOperationParameters:
    - name: access_token
      description: user access token
      modelRef: string
      parameterType: header
      required: true

# Mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 自增 ID
      id-type: AUTO
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  mapper-locations: classpath*:com/whale/framework/repository/mapper/**/*.xml
  # 扫描model实体对象
  type-aliases-package: com.whale.framework.repository.model.*.*
  configuration:
    # 日志控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
